services:
  api:
    image: emal-auto:latest
    build: .
    command: ["node", "dist/server.js"]
    ports:
      - "${SERVER_PORT:-3737}:${SERVER_PORT:-3737}"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - default
      - redis_net

  worker:
    image: emal-auto:latest
    build: .
    command: ["node", "dist/worker.js"]
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - default
      - redis_net

networks:
  redis_net:
    external: true
    name: docker_default