/**
 * Read GRAPH_APP_<N>_DOMAIN / _TENANT_ID / _CLIENT_ID / _CLIENT_SECRET from .env
 * (same rules as `readGraphAppsFromEnv` in src/config/index.ts) and print
 * idempotent INSERT ... ON CONFLICT (domain) DO UPDATE for `graph_apps`.
 *
 * Usage:
 *   npx tsx scripts/env-graph-apps-to-sql.ts
 *   npx tsx scripts/env-graph-apps-to-sql.ts --env /path/to/.env
 *   npm run graph-apps:sql > graph-apps-seed.generated.sql
 *
 * Do not commit generated SQL (contains client_secret).
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import dotenv from "dotenv";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");

function parseArgs(): { envPath: string } {
  const argv = process.argv.slice(2);
  let envPath = path.join(repoRoot, ".env");
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--env" && argv[i + 1]) {
      envPath = path.resolve(argv[i + 1]!);
      i++;
    }
  }
  return { envPath };
}

/** PostgreSQL dollar-quote; delimiter must not appear inside `s`. */
function dollarQuote(s: string): string {
  for (let n = 0; ; n++) {
    const tag = `g${n}`;
    const delim = `$${tag}$`;
    if (!s.includes(delim)) return `${delim}${s}${delim}`;
  }
}

function readGraphAppsFromEnvMap(env: NodeJS.ProcessEnv): Array<{
  domain: string;
  tenant_id: string;
  client_id: string;
  client_secret: string;
}> {
  const rows: Array<{
    domain: string;
    tenant_id: string;
    client_id: string;
    client_secret: string;
  }> = [];
  for (let i = 1; i < 100; i++) {
    const domain = env[`GRAPH_APP_${i}_DOMAIN`];
    if (!domain?.trim()) break;
    const tenant_id = env[`GRAPH_APP_${i}_TENANT_ID`]?.trim();
    const client_id = env[`GRAPH_APP_${i}_CLIENT_ID`]?.trim();
    const client_secret = env[`GRAPH_APP_${i}_CLIENT_SECRET`]?.trim();
    if (!tenant_id || !client_id || !client_secret) {
      throw new Error(
        `GRAPH_APP_${i}_DOMAIN is set but missing _TENANT_ID / _CLIENT_ID / _CLIENT_SECRET`,
      );
    }
    rows.push({
      domain: domain.trim().toLowerCase(),
      tenant_id,
      client_id,
      client_secret,
    });
  }
  return rows;
}

function main(): void {
  const { envPath } = parseArgs();
  if (!fs.existsSync(envPath)) {
    console.error(`env file not found: ${envPath}`);
    process.exit(1);
  }
  dotenv.config({ path: envPath });
  const rows = readGraphAppsFromEnvMap(process.env);
  if (rows.length === 0) {
    console.error("No GRAPH_APP_1_DOMAIN (etc.) found in env.");
    process.exit(1);
  }

  const lines: string[] = [
    "-- Generated by scripts/env-graph-apps-to-sql.ts",
    "-- After apply: set GRAPH_APPS_SOURCE=db in .env and restart api + worker.",
    "",
    "INSERT INTO graph_apps (domain, tenant_id, client_id, client_secret, enabled)",
    "VALUES",
  ];

  const valueLines = rows.map((r, idx) => {
    const comma = idx < rows.length - 1 ? "," : "";
    return `  (${dollarQuote(r.domain)}, ${dollarQuote(r.tenant_id)}, ${dollarQuote(r.client_id)}, ${dollarQuote(r.client_secret)}, true)${comma}`;
  });
  lines.push(...valueLines);
  lines.push("ON CONFLICT (domain) DO UPDATE SET");
  lines.push("  tenant_id = EXCLUDED.tenant_id,");
  lines.push("  client_id = EXCLUDED.client_id,");
  lines.push("  client_secret = EXCLUDED.client_secret,");
  lines.push("  enabled = EXCLUDED.enabled,");
  lines.push("  updated_at = now();");
  lines.push("");

  process.stdout.write(lines.join("\n"));
}

main();
